# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Message
  displayName: Message
  jobs:
  - job: Message
    pool: server
    displayName: Message
    steps:
    - task: PublishToAzureServiceBus@1
      inputs:
        azureSubscription: message
        messageBody: |
           {"message": "Hello World!"}
        waitForCompletion: false
        useDataContractSerializer: false