# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Message
  displayName: Message
  jobs:
  - job: Message
    pool: server
    displayName: Message
    steps:
    - task: PublishToAzureServiceBus@1
      inputs:
        azureSubscription: "a36d11dd-43d4-4905-9a36-3c5d48ff219c"
        messageBody: "hello world"
        waitForCompletion: false

- stage: Build
  displayName: Build image
  pool: 
   name: pool-test
   demands:
    - agent.name -equals Agentname
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps: 
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(System.DefaultWorkingDirectory)/hello-chris/Dockerfile'
        tags: |
          $(tag)
