apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: hello-chris-eventlistener 
spec:
  serviceAccountName: pipeline
  triggers:
    - name: hello-chris-trigger
      interceptors:
        - cel:
            filter: >-
               body.contains("/src")
            overlays:
              - key: intercepted.working-dir
                expression: "'/src'"
      bindings:
        - name: hello-chris-binding
      template:
        name: hello-chris-template
    - name: hello-dave-trigger
      interceptors:
        - cel:
            filter: >-
               body.contains("/src2")
            overlays:
              - key: intercepted.working-dir
                expression: "'/src2'"
      bindings:
        - name: hello-chris-binding
      template:
        name: hello-chris-template
