---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: hello-chris-binding 
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.git_ssh_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.commits[0].id)

